# Generated by Django 3.2.9 on 2021-11-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0002_alter_testmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name': 'Test Model'},
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
