# Generated by Django 3.2.9 on 2021-11-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0003_auto_20211108_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
