version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "8000:5432"
    networks:
      - postgres
    restart: unless-stopped

  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/code
  # redis:
  #   image: redis


networks:
  postgres:
    driver: bridge

volumes:
  postgres:

  