version: '3'
services: 
  postgres:
    image: postgres
    container_name: fat_postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '8000:5432'
    volumes:
      - .postgres:/data/postgres
    networks:
      - postgres
    restart: always
volumes:
  postgres:
networks:
  postgres:
    driver: bridge